app:
    resource: '@AppBundle/Controller/'
    type: annotation

some:
    path:     /some/{page}
    defaults: { _controller: "AppBundle:Default:some" }
    
resume:
    resource: '@AppBundle/Resources/config/routing/resume.yml'
    prefix: resume